### ISSUE TITLE
index.html file missing

### ISSUE THREAD

**Issue by sumitsumo** [anchetaWern/ElectronWhiteboard#1]
Could not find a required file.
  Name: index.html
  Searched in: C:\Users\SUMIT\Desktop\ElectronWhiteboard\public
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electronwhiteboard@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electronwhiteboard@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by sumitsumo** [comment]
my bad

**Comment by omrihaim** [comment]
hey @sumitsumo can you add you solution for others who bump into the same issue? Thanks
